import styled from 'styled-components'
import { MainST } from "../components/sharedstyles";
import Head from "next/head";
import ImageWrapper from '../components/ImageWrapper';
import SideMenu from '@/components/SideMenu';
import { useState } from 'react';
import Pin from '@/components/Pin';

const data = {name:"Nome", color:"", pinList: [
  {title:"Pin1", text: "Lorem ipsum dolor at a met 1", posX: 30, posY: 30},
  {title:"Pin2", text: "Lorem ipsum dolor at a met 2", posX: 20, posY: 20},
  {title:"Pin1", text: "Lorem ipsum dolor at a met 1", posX: 50, posY: 50},
  {title:"Pin2", text: "Lorem ipsum dolor at a met 2", posX: 60, posY: 60},
]}

export default function Home() {

  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Pinmap App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainST>
        <ImageWrapper shrink={menuOpen} >
          {
             data.pinList.map((pin, index) => (
              <Pin key={index} number={index + 1} posY={pin.posY} posX={pin.posX} color="#144ea5" />
             ))
          }
        </ImageWrapper>
        <SideMenu
          isOpen={menuOpen}
          data={data}
          handler={ () => setMenuOpen(!menuOpen) } />
      </MainST>
    </>
  );
}